"""Add flag for dispensed drugs in patient_drug table

Revision ID: 023175a71eb6
Revises: 68a5ed73ab1d
Create Date: 2018-03-03 09:45:45.664000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023175a71eb6'
down_revision = '68a5ed73ab1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_drug', sa.Column('dispensed', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_patient_drug_dispensed'), 'patient_drug', ['dispensed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_drug_dispensed'), table_name='patient_drug')
    op.drop_column('patient_drug', 'dispensed')
    # ### end Alembic commands ###
