"""Added PatientDrug Association Class

Revision ID: 2a1be09d2c47
Revises: be7bedeec86f
Create Date: 2018-02-21 21:38:33.408000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1be09d2c47'
down_revision = 'be7bedeec86f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_drug',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['drug.drug_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('patient_id', 'drug_id')
    )
    op.create_index(op.f('ix_patient_drug_qty'), 'patient_drug', ['qty'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_drug_qty'), table_name='patient_drug')
    op.drop_table('patient_drug')
    # ### end Alembic commands ###
